### ISSUE TITLE
Can't find QT Designer UI File 

### ISSUE THREAD

**Issue by xAkai97** [marcpinet/bulk-download-from-nyaa.si#2]
Looking for to original QT Designer .ui file before it was converted to gui.py.

**Comment by marcpinet** [comment]
No problem! I didn't expect someone who would want this file. Anyway, I just uploaded it, so you now have access to it.
=> https://github.com/marcpinet/batch-downloader-nyaa.si/tree/main/pyqt-ui

Please, note that this file only contains the GUI with the widgets put at the right place. Method connections, etc. are only in the .py.
