### ISSUE TITLE
Download doesn't work (for me only)

### ISSUE THREAD

**Issue by kinetictreaty** [marcpinet/bulk-download-from-nyaa.si#4]
The application closes, shows "failed: 'Anime name - Episode Number'", or shows "this anime is not in nyaa database" (I made sure it was from nyaa too)

This is happening in all three versions.
 Either of the two issues written above happens or the app closes.
![error 1](https://user-images.githubusercontent.com/102519793/160381417-40836c5d-5edf-47a4-8fc9-3affcb639595.jpeg)
![error 2](https://user-images.githubusercontent.com/102519793/160381423-d61f470b-c022-4cde-9a94-981843ace4c1.jpeg)

**Comment by marcpinet** [comment]
Hello, I tried on my machine and on a virtual machine but it does actually work. Can you give me more details please? (Windows ver., Python ver., etc.)

**Comment by kinetictreaty** [comment]
Sure, I've got Windows 10 pro, version 1909. I don't have python.

**Comment by marcpinet** [comment]
> Sure, I've got Windows 10 pro, version 1909. I don't have python.

Are you using the last version of the .exe? Also, is your firewall blocking something that the program might be using?

**Comment by kinetictreaty** [comment]
I'm using the latest version, and I'm not sure about the firewall blocking something, so I excluded the folder nyaadownloader was in from virus sscans, but it still shows "this anime is not in nyaa data base"

**Comment by marcpinet** [comment]
> I'm using the latest version, and I'm not sure about the firewall blocking something, so I excluded the folder nyaadownloader was in from virus sscans, but it still shows "this anime is not in nyaa data base"

Are you using a VPN or something that might be blocking the program?

**Comment by kinetictreaty** [comment]
not using a vpn. is there something else that might be blocking it other than vpn and firewall?

**Comment by marcpinet** [comment]
> not using a vpn. is there something else that might be blocking it other than vpn and firewall?

I don't really think. Can you try the Python version if possible?

**Comment by kinetictreaty** [comment]
python version, is the first version?

**Comment by marcpinet** [comment]
> python version, is the first version?

https://www.python.org/ftp/python/3.9.1/python-3.9.1-amd64.exe

Try the same as mine to see if there is something wrong with the .exe one. Also, if you don't have git to clone this repository, you can just download it by clicking on the green button "Code" above the repo and click Download as .zip, then extract it and you should run "pip install -r requirements.txt" just after you `cd` in the terminal to the directory (feel free to ask me anything if you don't understand what I've just said)

**Comment by kinetictreaty** [comment]
I'll try it out. thanks

**Comment by kinetictreaty** [comment]
> 

could you please explain the last part ("pip install -r requirements.txt" just after you cd in the terminal to the directory)

**Comment by marcpinet** [comment]
> > 
> 
> could you please explain the last part ("pip install -r requirements.txt" just after you cd in the terminal to the directory)

Okay so, once you downloaded the folder, you need to open the terminal (the cmd) and the type `cd path\to\your\directory` (replace the "path\to\your\directory" by the absolute path of where the directory is located on your computer (probably something like C:\Users\<your_username>\Downloads\NyaaDownloader)

After that, use the command `pip install -r requirements.txt` in order to install the requirements. Because you need the requirements.txt file, you also need to be in the same directory as it.

**Comment by marcpinet** [comment]
If you can't succeed, just type these commands :

`pip install nyaapy==0.6.1`
`winotify==1.0.4`
`requests==2.25.1`
`PyQt5==5.15.4`

It will be the same actually (but less simple). Anyway, after that you just need to execute the main.pyw file and tell me if it is still bugging.

**Comment by kinetictreaty** [comment]
> > > 
> > 
> > 
> > could you please explain the last part ("pip install -r requirements.txt" just after you cd in the terminal to the directory)
> 
> Okay so, once you downloaded the folder, you need to open the terminal (the cmd) and the type `cd path\to\your\directory` (replace the "path\to\your\directory" by the absolute path of where the directory is located on your computer (probably something like C:\Users<your_username>\Downloads\NyaaDownloader)
> 
> After that, use the command `pip install -r requirements.txt` in order to install the requirements. Because you need the requirements.txt file, you also need to be in the same directory as it.

what is the terminal/cmd?

**Comment by marcpinet** [comment]
> 
> > > > 
> > > 
> > > 
> > > could you please explain the last part ("pip install -r requirements.txt" just after you cd in the terminal to the directory)
> > 
> > Okay so, once you downloaded the folder, you need to open the terminal (the cmd) and the type `cd path\to\your\directory` (replace the "path\to\your\directory" by the absolute path of where the directory is located on your computer (probably something like C:\Users<your_username>\Downloads\NyaaDownloader)
> > 
> > After that, use the command `pip install -r requirements.txt` in order to install the requirements. Because you need the requirements.txt file, you also need to be in the same directory as it.
> 
> what is the terminal/cmd?


Open Windows Search and type cmd

**Comment by kinetictreaty** [comment]
sorry for replying so late, but I have done everything. what should I do now?

**Comment by marcpinet** [comment]
> sorry for replying so late, but I have done everything. what should I do now?

Now you should run the main.pyw and tell me what it does

**Comment by kinetictreaty** [comment]
nyaa downloader starts but it's still showing error

**Comment by marcpinet** [comment]
> nyaa downloader starts but it's still showing error

Okay so it seems that the issue is only affecting you. I tried on different computers and it works perfectly. You probably have something that avoids any request from the script. Maybe try disabling any running antivirus to see if it works? (unless you're using Windows Defender which should not be blocking anything from NyaaDownloader)

**Comment by kinetictreaty** [comment]
It must be the anitivirus. I excluded the folder nyaadownloader is in from the antivirus settings, but it still shows error. It's ok if it's not happening with any other device. thank you for taking out the time.
