### ISSUE TITLE
Add a button to enable unverified torrent checking to allow search for anonymous uploaders

### ISSUE THREAD

**Issue by Pulkit3108** [marcpinet/bulk-download-from-nyaa.si#5]
Will this work if the uploader is Anonymous and not from subsplease or eral-raws

**Comment by marcpinet** [comment]
Atm, since it only looks for verified torrents (to avoid any potential threat) by default, no.
However I can add a button to enable unverified torrents and you will be able to download torrents from anonymous people.

Adding this to the To-Do list ✅

**Comment by marcpinet** [comment]
I have no idea when I will do that, but when it'll be done, I'll let you know.

**Comment by marcpinet** [comment]
Done.
