### ISSUE TITLE
UI Scaling borked

### ISSUE THREAD

**Issue by mr-september** [marcpinet/bulk-download-from-nyaa.si#8]
1. The default UI size is not large enough to show everything, especially the buttons at the bottom
2. Window resizing does not work. The bottom right corner suggests it does, but it does nothing.

![image](https://github.com/marcpinet/nyaadownloader/assets/45350177/2b55f245-d753-4238-83f3-08dd126d495e)

**Comment by marcpinet** [comment]
it has been a long time since I didn't update this project
you seem to have a non conventional screen zoom (probably 125% or more in your windows settings), i'm guessing it's a laptop

however, i will fix that quickly for you don't worry 👍🏻

**Comment by marcpinet** [comment]
done, fixed
